### ISSUE TITLE
Switch to font parser from x/image/font

### ISSUE THREAD

**Issue by dennwc** [unidoc/unidoc#282]
Currently, Unidoc maintains a custom TTF font parser, while [x/image/font](https://godoc.org/golang.org/x/image/font) already provides the [one](https://godoc.org/golang.org/x/image/font/sfnt#Parse) that more closely follow the spec.

The proposal is to drop current implementation in favor of parser from `x/image/font`.

In the long run, this will also allow using text rendering libraries available in `x/image` to render PDF documents.

Initial testing shows that integration will not be as painful as one may imagine, but it requires changes to Unidoc (to define font interface cleanly) and to `x/image/font` (to support some legacy font formats seen in the wild).

This issue will track progress on this integration.

**Changes to `x/image/font`:**
- [x] Support fonts with `true` version tag ([CL 146078](https://go-review.googlesource.com/c/image/+/146078))
- [x] Support `post` table version 1.0 ([CL 146080](https://go-review.googlesource.com/c/image/+/146080))
- [x] Support OS2 table version 1 ([#28339](https://github.com/golang/go/issues/28339), [CL 144079](https://go-review.googlesource.com/c/image/+/144079))
- [x] Expose PostScript information ([CL 145797](https://go-review.googlesource.com/c/image/+/145797))
- [x] Fix `hmtx` header validation ([#28379](https://github.com/golang/go/issues/28379), [CL 144080](https://go-review.googlesource.com/c/image/+/144080))
- [ ] Support `cmap` format 6 ([CL 146079](https://go-review.googlesource.com/c/image/+/146079))
- [ ] Define an initial cmap interface ([CL 146077](https://go-review.googlesource.com/c/image/+/146077))
- [ ] Expose font selection flags ([CL 145798](https://go-review.googlesource.com/c/image/+/145798))
- [ ] Add parsing tests for legacy fonts ([CL 146081](https://go-review.googlesource.com/c/image/+/146081))
- [ ] Support other cmap formats supported by Unidoc
- [ ] Expose character ranges in cmaps
- [ ] Fix few more small issues with legacy font validation

**Changes to Unidoc:**
- [x] Add tests to track any regressions during transition ([#248](https://github.com/unidoc/unidoc/pull/248))
- [ ] Clarify all rune<->charcode<->glyph conversions ([#259](https://github.com/unidoc/unidoc/pull/259), [#260](https://github.com/unidoc/unidoc/pull/260))
- [ ] Define a clean font and encoder interfaces
- [ ] Implement interfaces based on `x/image/font`
